### PR TITLE
use project.afterEvaluate {} to defer configuration

### LINKED ISSUE #16: How to generate output?
I have a next file structure:

```
app
   - src
       - main
            - groovy
                 - proto-output
           - proto-files
                first.proto

```

then in my `build.gradle`

``` groovy
apply plugin: 'groovy'
apply plugin: 'protobuf'

version = '0.0.1'

group = 'com.example'
sourceCompatibility = 1.6

def appName = 'app'

ext {
    groovyVersion = '2.3.6'
}

repositories {
    mavenCentral()
}

dependencies {
  compile 'org.codehaus.groovy:groovy-all:2.3.6'
  compile 'com.google.protobuf:protobuf-java:2.5.0'
}


buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'ws.antonov.gradle.plugins:gradle-plugin-protobuf:0.9.1'
    }
}



extractedProtosDir = "${projectDir}/src/main/proto-files"

generatedFileDir = "${projectDir}/src/main/groovy/ proto-output"
```

but when i do  `gradle build` i not see in `proto-output` generated files, why?

### PR DESCRIPTION
**Pull request by jberkel**
Fixes #16 

Not sure what other side-effect this has, but works fine so far in my project.

see http://stackoverflow.com/a/25388282 for a discussion

### CODE REVIEW

**Comment by jberkel** [comment]
is this project ✞ ?

**Comment by aantono** [comment]
The project is very well alive...  I'm trying to rewrite the plugin using the latest Gradle 2.x additions to the API/cleanup, so didn't want to release just a patch.
How critical is this issue for your usage?

**Comment by jberkel** [comment]
it doesn't build properly without it, and I have a CI setup which constantly fails because of this, but it's not critical as long as there will be an update at some point

**Comment by aantono** [comment]
I would expect it to be fairly soon... I have some cleanup to be done and then decide how to handle (if there is a better, common-case way) #22

**Comment by jberkel** [comment]
ok, good to know. i like protobuf as a technology but tool support is still really bad. and i don't understand why google doesn't treat this as high priority, since it potentially hinders adoption. oh well.

**Pull request merged**
